export const data = [
    {
      postID: 1,
      name: "Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2019",
      date: "2019-05-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Sophomore",
      prerequisites: "Freshmen Chemistry",
      major: "Chemistry"
  
    },
    {
      postID: 2,
      name: "Photocatalysis Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2019",
      date: "2019-09-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Senior",
      prerequisites: "Freshmen Chemistry",
      major: "Chemistry"
    },
    {
      postID: 3,
      name: "Solar Energy Conversion Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2020-10-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Junior",
      prerequisites: "Freshmen Chemistry",
      major: "CS"
    },
    {
      postID: 4,
      name: "Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2021-11-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Senior",
      prerequisites: "Freshmen Chemistry",
      major: "Physics"
    },
    {
      postID: 5,
      name: "Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2021-11-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Junior",
      prerequisites: "Freshmen Chemistry",
      major: "Math"
    },
    {
      postID: 6,
      name: "Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2021-11-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Junior",
      prerequisites: "Freshmen Chemistry",
      major: "Chemistry"
    },
  ];