export const data = [
    {
      postID: 1,
      name: "Chem Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "//logo.clearbit.com/emory.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2020",
      date: "2019-05-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Sophomore",
      prerequisites: "Freshmen Chemistry",
      major: "Chemistry"
  
    },
    {
      postID: 2,
      name: "Chem Photocatalysis Research",
      professor: "Emily Dalton",
      school: "MIT",
      schoolLogo: "//logo.clearbit.com/mit.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Fall 2019",
      date: "2019-09-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Senior",
      prerequisites: "Freshmen Chemistry",
      major: "Chemistry"
    },
    {
      postID: 3,
      name: "CS Solar Energy Conversion Research",
      professor: "James Dalton",
      school: "Harvard University",
      schoolLogo: "//logo.clearbit.com/harvard.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2020-10-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Junior",
      prerequisites: "Freshmen Chemistry",
      major: "CS"
    },
    {
      postID: 4,
      name: "Phys Amino Acid Research",
      professor: "Lauren Dalton",
      school: "Stanford University",
      schoolLogo: "//logo.clearbit.com/stanford.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Fall 2021",
      date: "2021-11-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Senior",
      prerequisites: "Freshmen Chemistry",
      major: "Physics"
    },
    {
      postID: 5,
      name: "Math Amino Acid Research",
      professor: "Mark Dalton",
      school: "Georgia Tech Institue",
      schoolLogo: "//logo.clearbit.com/gatech.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2021-11-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Junior",
      prerequisites: "Freshmen Chemistry",
      major: "Math"
    },
    {
      postID: 6,
      name: "Chem Amino Acid Research",
      professor: "John Dalton",
      school: "Georgia State University",
      schoolLogo: "//logo.clearbit.com/gsu.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      date: "2021-11-09T12:32:02Z",
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: "Junior",
      prerequisites: "Freshmen Chemistry",
      major: "Chemistry"
    },
  ];