export const tempData = [
    {
      _id: 1,
      name: "Chem Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "emory.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      postDate: "2022-01-20T00:00:00.000Z",
      fromDate: "2022-02-07T00:00:00.000Z",
      toDate: "2022-04-20T00:00:00.000Z",
      daysOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: ["1", "2"],
      prerequisites: ["CHEM 150"],
      major: ["Chemistry"],
      applicants: [["1", "0"]],
      professorID: 1
    },
    {
      _id: 2,
      name: "Machine Learning: ASL Recognition",
      professor: "Han Motion",
      school: "Emory University",
      schoolLogo: "emory.edu",
      department: "Computer Science",
      postBody: "The CS department in partnership with the DIVR Data Reognition team from New York are looking into improving current accessibility across several alternative languages for people with dissabilities.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      postDate: "2022-02-01T00:00:00.000Z",
      fromDate: "2022-02-07T00:00:00.000Z",
      toDate: "2022-04-20T00:00:00.000Z",
      daysOfWeek: ["tuesday", "thursday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 0,
      isGrad: false,
      year: ["1", "2"],
      prerequisites: ["N/A"],
      major: ["N/A"],
      applicants: [["1", "1"]],
      professorID: 1
    },
    {
      _id: 3,
      name: "Chem Photocatalysis Research",
      professor: "Emily Dalton",
      school: "Massachusetts Institute of Technology",
      schoolLogo: "www.mit.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "77 Massachusetts Ave, Cambridge, MA 02139",
      activePost: true,
      semester: "Fall 2021",
      postDate: "2021-07-15T00:00:00.000Z",
      fromDate: "2021-09-20T00:00:00.000Z",
      toDate: "2021-11-17T00:00:00.000Z",
      daysOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.5,
      isGrad: false,
      year: ["4"],
      prerequisites: ["CHEM 150"],
      major: ["Chemistry"],
      applicants: [["1", "2"]],
      professorID: 1
    },
    {
      _id: 4,
      name: "CS Solar Energy Conversion Research",
      professor: "James Dalton",
      school: "Harvard University",
      schoolLogo: "www.harvard.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "Harvard University Massachusetts Hall Cambridge, MA 02138",
      activePost: true,
      semester: "Spring 2022",
      postDate: "2021-06-01T00:00:00.000Z",
      fromDate: "2021-09-21T00:00:00.000Z",
      toDate: "2021-10-23T00:00:00.000Z",
      daysOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      gpa: 3.2,
      isGrad: false,
      year: ["2"],
      prerequisites: ["CS 170", "PHYS 141"],
      major: ["Computer Science", "Physics"],
      applicants: [["2", "2"],["1", "0"],["4", "2"]],
      professorID: 1
    },
    {
      _id: 5,
      name: "Untitled Physics Research",
      professor: "Lauren Dalton",
      school: "Stanford University",
      schoolLogo: "www.stanford.edu",
      department: "Chemistry",
      postBody: "Information about this opportunity is private, apply to learn more.",
      isOnline: true,
      location: "450 Serra Mall, Stanford, CA 94305",
      activePost: true,
      semester: "Fall 2021",
      postDate: "2021-08-28T00:00:00.000Z",
      fromDate: "2021-09-20T00:00:00.000Z",
      toDate: "2021-11-19T00:00:00.000Z",
      daysOfWeek: ["friday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.0,
      isGrad: false,
      year: ["0"],
      prerequisites: ["PHYS 220"],
      major: ["Physics"],
      applicants: [["2", "2"],["1", "1"],["9", "1"]],
      professorID: 1
    },
    {
      _id: 6,
      name: "Untitled Physics Research",
      professor: "Lauren Dalton",
      school: "Stanford University",
      schoolLogo: "www.stanford.edu",
      department: "Chemistry",
      postBody: "Information about this opportunity is private, apply to learn more.",
      isOnline: true,
      location: "450 Serra Mall, Stanford, CA 94305",
      activePost: true,
      semester: "Fall 2021",
      postDate: "2021-08-28T00:00:00.000Z",
      fromDate: "2021-09-20T00:00:00.000Z",
      toDate: "2021-11-19T00:00:00.000Z",
      daysOfWeek: ["friday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      gpa: 3.0,
      isGrad: false,
      year: ["0"],
      prerequisites: ["PHYS 220"],
      major: ["Physics"],
      applicants: [["2", "2"],["1", "2"],["9", "0"]],
      professorID: 1
    },










  ];
