export const tempData = [
    {
      postID: 1,
      name: "Chem Amino Acid Research",
      professor: "John Dalton",
      school: "Emory University",
      schoolLogo: "emory.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      toDate: "2022-04-20T04:00:00.000Z",
      fromDate: "2022-02-07T05:00:00.000Z",
      dayOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      requirments: {
        gpa: 3.5,
        isGrad: false,
        year: ["second-year"],
        prerequisites: ["CHEM 150"],
        major: ["Chemistry"]

      }
    },
        {
      postID: 2,
      name: "Machine Learning: ASL Recognition",
      professor: "Han Motion",
      school: "Emory University",
      schoolLogo: "emory.edu",
      department: "Computer Science",
      postBody: "The CS department in partnership with the DIVR Data Reognition team from New York are looking into improving current accessibility across several alternative languages for people with dissabilities.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      toDate: "2022-04-20T04:00:00.000Z",
      fromDate: "2022-02-07T05:00:00.000Z",
      dayOfWeek: ["tuesday", "thursday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      requirments: {
        gpa: null,
        isGrad: false,
        year: ["first-year", "second-year"],
        prerequisites: null,
        major: null

      }
    },
    {
      postID: 3,
      name: "Chem Photocatalysis Research",
      professor: "Emily Dalton",
      school: "Massachusetts Institute of Technology",
      schoolLogo: "www.mit.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Fall 2021",
      toDate: "2021-11-17T05:00:00.000Z",
      fromDate: "2021-09-20T04:00:00.000Z",
      dayOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      requirments: {
        gpa: 3.5,
        isGrad: false,
        year: ["fourth-year"],
        prerequisites: ["CHEM 150"],
        major: ["Chemistry"]
      }
    },
    {
      postID: 4,
      name: "CS Solar Energy Conversion Research",
      professor: "James Dalton",
      school: "Harvard University",
      schoolLogo: "www.harvard.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      toDate: "2022-04-20T04:00:00.000Z",
      fromDate: "2022-02-07T05:00:00.000Z",
      dayOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: false,
      payAmount: 0,
      requirments: {
          gpa: 3.2,
          isGrad: false,
          year: ["second-year"],
          prerequisites: ["CS 170", "PHYS 141"],
          major: ["Computer Science", "Physics"]
      }
    },
    {
      postID: 5,
      name: "Untitled Physics Research",
      professor: "Lauren Dalton",
      school: "Stanford University",
      schoolLogo: "www.stanford.edu",
      department: "Chemistry",
      postBody: "Information about this opportunity is private, apply to learn more.",
      isOnline: true,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Fall 2021",
      toDate: "2021-11-19T05:00:00.000Z",
      fromDate: "2021-09-20T04:00:00.000Z",
      dayOfWeek: ["friday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      requirments: {
        gpa: 3.0,
        isGrad: false,
        year: null,
        prerequisites: ["PHYS 220"],
        major: ["Physics"]
      }
    },
    {
      postID: 6,
      name: "Euler Research",
      professor: "Mark Dalton",
      school: "Georgia Institute of Technology",
      schoolLogo: "www.gatech.edu",
      department: "Mathematics",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Fall 2022",
      toDate: "2022-11-03T04:00:00.000Z",
      fromDate: "2022-09-20T04:00:00.000Z",
      dayOfWeek: ["tuesday", "thursday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      requirments: {
        gpa: 3.5,
        isGrad: false,
        year: ["third-year"],
        prerequisites: ["MATH 111", "MATH 112", "MATH 221"],
        major: ["Mathematics"]
      }
    },
    {
      postID: 7,
      name: "Chem Amino Acid Research",
      professor: "John Dalton",
      school: "Georgia State University",
      schoolLogo: "gsu.edu",
      department: "Chemistry",
      postBody: "We invite students from both 4-year and 2-year universities, as well as students from community colleges to apply. For most labs, only completion of freshmen chemistry and lab is required. Organic classes and lab are required for some, but not all organic labs.",
      isOnline: false,
      location: "201 Dowman Dr, Atlanta, GA 30322",
      activePost: true,
      semester: "Spring 2022",
      toDate: "2022-04-20T04:00:00.000Z",
      fromDate: "2022-02-07T05:00:00.000Z",
      dayOfWeek: ["monday", "wednesday"],
      timeRange: "16:00-20:00",
      isPaid: true,
      payAmount: 0,
      requirments: {
        gpa: 3.7,
        isGrad: false,
        year: null,
        prerequisites: ["CHEM 150"],
        major: ["Chemistry"]
      }
    },
  ];
